

-- 16. NOTIFICATIONS
DROP TABLE IF EXISTS notifications CASCADE;
-- 15. PAYMENTS
DROP TABLE IF EXISTS payments CASCADE;
-- 14.1 ORDER_ITEM_MATERIALS
DROP TABLE IF EXISTS order_item_materials CASCADE;
-- 14. ORDER_ITEMS
DROP TABLE IF EXISTS order_items CASCADE;
-- 13. ORDERS
DROP TABLE IF EXISTS orders CASCADE;
-- 12. INVENTORY_TRANSACTIONS
DROP TABLE IF EXISTS inventory_transactions CASCADE;
-- 11.5 INVENTORY_DOCUMENT_ITEMS
DROP TABLE IF EXISTS inventory_document_items CASCADE;
-- 11.5 INVENTORY_DOCUMENTS
DROP TABLE IF EXISTS inventory_documents CASCADE;
-- 11.5 SUPPLIERS
DROP TABLE IF EXISTS suppliers CASCADE;
-- 11. APPOINTMENT_ITEMS
DROP TABLE IF EXISTS appointment_items CASCADE;
-- 10. APPOINTMENTS
DROP TABLE IF EXISTS appointments CASCADE;
-- 9. BLACKLISTS
DROP TABLE IF EXISTS blacklists CASCADE;
-- 8. SERVICE_MATERIALS
DROP TABLE IF EXISTS service_materials CASCADE;
-- 7. PRODUCTS
DROP TABLE IF EXISTS products CASCADE;
-- 6. SERVICES
DROP TABLE IF EXISTS services CASCADE;
-- 5. CATEGORIES
DROP TABLE IF EXISTS categories CASCADE;
-- 4. STAFF
DROP TABLE IF EXISTS staff CASCADE;
-- 3. CUSTOMERS
DROP TABLE IF EXISTS customers CASCADE;
-- 2. USERS
DROP TABLE IF EXISTS users CASCADE;
-- 1. ORGANIZATIONS
DROP TABLE IF EXISTS organizations CASCADE;

-- Functions dùng chung (CASCADE kéo trigger còn sót nếu có)
DROP FUNCTION IF EXISTS set_updated_at() CASCADE;
DROP FUNCTION IF EXISTS check_product_web_visibility() CASCADE;
